Vagrant.configure("2") do |config|
  # === OS image ===
  config.vm.box = "ubuntu/jammy64"

  # === VirtualBox nastavitve ===
  config.vm.provider "virtualbox" do |vb|
    vb.name = "report-app-devops"
    vb.memory = 4096
    vb.cpus = 2
    vb.gui = true

    # DNS fix, da ne izgubiš povezave med apt update (izogib 'Temporary failure resolving')
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # === Port forwarding ===
  config.vm.network "forwarded_port", guest: 80,  host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
  config.vm.network "forwarded_port", guest: 3389, host: 33389, auto_correct: true

  # === Synced folder ===
  config.vm.synced_folder ".", "/vagrant", SharedFoldersEnableSymlinksCreate: false

  # === Provisioners ===
  # 1. Namesti Ansible
  config.vm.provision "shell", path: "provision-base.sh"

  # 2. Zaženi Ansible playbook
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/ansible/playbook.yml"
    ansible.inventory_path = "/vagrant/ansible/inventory"
    ansible.limit = "all"
  end
end
